Repository GSG-G13/code-academy-api, pull requests merged in 2023-06, with the labels that each got.

#4 create file structure for our api
  .eslintrc.json
  .gitignore
  example.env
  package-lock.json
  package.json
  src/app.ts
  src/config/index.ts
  src/controllers/index.ts
  src/database/config/build.sql
  src/database/config/connection.ts
  src/database/config/fakeData.sql
  src/database/config/index.ts
  src/database/index.ts
  src/database/query/index.ts
  src/index.ts
  src/middlewares/index.ts
  src/routes/index.ts
  src/utils/helpers/index.ts
  src/utils/index.ts
  src/utils/jwt/index.ts
  src/utils/types/index.ts
  src/utils/validation/index.ts
  tsconfig.json
Labels: awaiting-review, back-end

#8 create connection file
  example.env
  package-lock.json
  package.json
  src/config/index.ts
  src/database/config/connection.ts
  src/database/config/index.ts
Labels: awaiting-review

#5 create database and fake data relates #2
  src/database/config/build.sql
  src/database/config/fakeData.sql
Labels: awaiting-review, database, fake-data

#11 fix fakedata file by add begin and commit
  src/database/config/fakeData.sql
Labels: awaiting-review, database

#20 get user by email query
  src/database/index.ts
  src/database/query/auth/getUserByEmailQuery.ts
  src/database/query/auth/index.ts
  src/database/query/index.ts
Labels: awaiting-review, back-end

#26 13 build bcrypt functions
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/utils/helpers/bcrypt/comparePassword.ts
  src/utils/helpers/bcrypt/hashPassword.ts
  src/utils/helpers/bcrypt/index.ts
  src/utils/helpers/index.ts
  src/utils/index.ts
Labels: awaiting-review, back-end

#18 fix fackdata file by add begin commit-1
  src/database/config/build.sql
Labels: awaiting-review, database

#31 Create add user validation schema
  src/utils/validation/auth/addUserSchema.ts
Labels: awaiting-review

#19 9-add-user ,checkemail and roles
  package-lock.json
  package.json
  src/config/index.ts
  src/database/config/build.sql
  src/database/query/admin/createUserQuery.ts
  src/database/query/admin/createUserRoleQuery.ts
  src/utils/email/sendEamil.ts
  src/utils/types/helpers/index.ts
  src/utils/types/helpers/roleType.ts
  src/utils/types/helpers/userType.ts
  src/utils/types/index.ts
Labels: awaiting-review

#33 rename and update schema
  src/utils/validation/auth/addUserSchema.ts
Labels: approved

#30 Create JWT functions (SignToken, VerifyToken)
  src/config/index.ts
  src/database/index.ts
  src/database/query/admin/createUserQuery.ts
  src/database/query/admin/createUserRoleQuery.ts
  src/database/query/auth/getUserByEmailQuery.ts
  src/database/query/auth/index.ts
  src/database/query/index.ts
  src/utils/index.ts
  src/utils/jwt/index.ts
  src/utils/jwt/signinToken.ts
  src/utils/jwt/verifyToken.ts
  src/utils/types/helpers/JwtPayload.ts
  src/utils/types/helpers/User.ts
  src/utils/types/helpers/index.ts
  src/utils/types/helpers/roleType.ts
  src/utils/types/index.ts
  src/utils/validation/auth/addUserSchema.ts
Labels: awaiting-review, back-end

#22 Create login validation schema
  src/utils/validation/auth/index.ts
  src/utils/validation/auth/loginSchema.ts
  src/utils/validation/index.ts
Labels: awaiting-review, back-end

#7 3-create-readmemd-file
  README.md
Labels: awaiting-review

#35 34 fix create login validation schema
  package-lock.json
  src/utils/validation/auth/index.ts
  src/utils/validation/auth/loginSchema.ts
  src/utils/validation/index.ts
Labels: approved, back-end

#38 Create Custom Error Class
  src/utils/helpers/CustomError/index.ts
  src/utils/helpers/index.ts
Labels: awaiting-review, back-end

#36 21 send email function
  src/config/index.ts
  src/utils/email/sendEmail.ts
Labels: awaiting-review

#40 14 login controller
  src/app.ts
  src/controllers/admin/auth/index.ts
  src/controllers/admin/auth/signInController.ts
  src/controllers/admin/index.ts
  src/controllers/index.ts
  src/database/config/fakeData.sql
  src/routes/admin/auth.ts
  src/routes/admin/index.ts
  src/routes/index.ts
  src/utils/jwt/signinToken.ts
  src/utils/types/helpers/JwtPayload.ts
Labels: awaiting-review, back-end

#42 41 handle error in controller
  src/app.ts
  src/controllers/admin/auth/signInController.ts
  src/controllers/errors/clientError.ts
  src/controllers/errors/index.ts
  src/controllers/errors/serverError.ts
  src/controllers/index.ts
  src/database/config/fakeData.sql
  src/routes/admin/auth.ts
Labels: awaiting-review, back-end

#48 46 create add cohort controller
  src/controllers/admin/addUsers.ts
  src/controllers/admin/auth/signInController.ts
  src/controllers/admin/cohorts/addCohortController.ts
  src/controllers/admin/cohorts/index.ts
  src/controllers/admin/index.ts
  src/controllers/index.ts
  src/database/index.ts
  src/database/query/admin/AddCohortQuery.ts
  src/database/query/admin/getCohortByNameQuery.ts
  src/database/query/admin/index.ts
  src/database/query/index.ts
  src/routes/admin/cohorts.ts
  src/routes/admin/index.ts
  src/routes/index.ts
  src/utils/index.ts
  src/utils/types/helpers/AddCohort.ts
  src/utils/types/helpers/index.ts
  src/utils/types/index.ts
  src/utils/validation/cohorts/addCohortSchema.ts
  src/utils/validation/cohorts/index.ts
  src/utils/validation/index.ts
Labels: awaiting-review

#49 39 create checkauth middleware
  src/controllers/admin/cohorts/addCohortController.ts
  src/controllers/admin/index.ts
  src/controllers/admin/users/addUsersController.ts
  src/controllers/admin/users/index.ts
  src/controllers/errors/serverError.ts
  src/controllers/index.ts
  src/database/config/build.sql
  src/database/index.ts
  src/database/query/admin/index.ts
  src/database/query/auth/getUserRoles.ts
  src/database/query/auth/index.ts
  src/database/query/index.ts
  src/middlewares/checkAuth.ts
  src/middlewares/index.ts
  src/routes/admin/users.ts
  src/routes/index.ts
  src/utils/index.ts
  src/utils/jwt/verifyToken.ts
  src/utils/types/helpers/CheckAuthRequest.ts
  src/utils/types/helpers/Decoded.ts
  src/utils/types/helpers/index.ts
  src/utils/types/index.ts
  src/utils/types/requests/index.ts
Labels: awaiting-review

#56 51 delete post route
  src/controllers/index.ts
  src/controllers/posts/deletePostController.ts
  src/controllers/posts/index.ts
  src/database/config/build.sql
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/posts/deletePostQuery.ts
  src/database/query/posts/getPostByIdQuery.ts
  src/database/query/posts/index.ts
  src/routes/index.ts
  src/routes/posts.ts
  src/utils/index.ts
  src/utils/types/requests/index.ts
  src/utils/validation/index.ts
  src/utils/validation/posts/deletePostSchema.ts
  src/utils/validation/posts/index.ts
Labels: approved, back-end

#55 Edit post controller
  src/controllers/index.ts
  src/controllers/posts/editPostController.ts
  src/controllers/posts/index.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/posts/editPostQuery.ts
  src/database/query/posts/index.ts
  src/routes/index.ts
  src/routes/posts/index.ts
  src/utils/email/sendEmail.ts
  src/utils/index.ts
  src/utils/types/helpers/index.ts
  src/utils/types/helpers/posts/EditPost.ts
  src/utils/types/helpers/posts/index.ts
  src/utils/types/index.ts
  src/utils/types/requests/index.ts
  src/utils/validation/index.ts
  src/utils/validation/posts/editPostSchema.ts
  src/utils/validation/posts/index.ts
Labels: awaiting-review, back-end

#59 Add post router
  .gitignore
  src/controllers/index.ts
  src/controllers/posts/addPost.ts
  src/controllers/posts/index.ts
  src/database/config/build.sql
  src/database/config/index.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/posts/addPostQuery.ts
  src/database/query/posts/index.ts
  src/routes/posts.ts
  src/utils/index.ts
  src/utils/types/helpers/Decoded.ts
  src/utils/types/helpers/index.ts
  src/utils/types/helpers/posts/AddPostQuery.ts
  src/utils/types/helpers/posts/index.ts
  src/utils/types/index.ts
  src/utils/types/requests/index.ts
  src/utils/validation/index.ts
  src/utils/validation/posts/addPostSchema.ts
  src/utils/validation/posts/index.ts
Labels: awaiting-review, back-end

#58 Get all posts route pagination
  .eslintrc.json
  .gitignore
  .prettierrc.js
  README.md
  commitlint.config.js
  src/controllers/admin/cohorts/addCohortController.ts
  src/controllers/index.ts
  src/controllers/posts/addPost.ts
  src/controllers/posts/deletePostController.ts
  src/controllers/posts/getCohortPostsController.ts
  src/controllers/posts/getPublicPostsController.ts
  src/controllers/posts/getSinglePostController.ts
  src/controllers/posts/index.ts
  src/database/config/build.sql
  src/database/config/fakeData.sql
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/posts/addPostQuery.ts
  src/database/query/posts/deletePostQuery.ts
  src/database/query/posts/getCohortIdByNameQuery.ts
  src/database/query/posts/getCohortPostsQuery.ts
  src/database/query/posts/getPostByIdQuery.ts
  src/database/query/posts/getPublicPostsQuery.ts
  src/database/query/posts/index.ts
  src/routes/posts.ts
  src/routes/posts/index.ts
  src/utils/helpers/bcrypt/hashPassword.ts
  src/utils/index.ts
  src/utils/types/helpers/CheckAuthRequest.ts
  src/utils/types/helpers/CohortNameQueryArgs.ts
  src/utils/types/helpers/CohortPostsQueryArgs.ts
  src/utils/types/helpers/PostIdQueryArgs.ts
  src/utils/types/helpers/PublicPostsQueryArgs.ts
  src/utils/types/helpers/index.ts
  src/utils/types/index.ts
  src/utils/types/requests/index.ts
  src/utils/validation/posts/addPostSchema.ts
  tsconfig.json
Labels: awaiting-review, back-end

#62 61 get one post
  src/database/config/build.sql
  src/routes/posts.ts
  src/utils/index.ts
  src/utils/types/helpers/index.ts
  src/utils/types/index.ts
Labels: awaiting-review

#68 64 get all cohorts route
  src/controllers/cohorts/getAllCohortsController.ts
  src/controllers/cohorts/index.ts
  src/controllers/index.ts
  src/database/index.ts
  src/database/query/cohorts/getAllCohortsQuery.ts
  src/database/query/cohorts/index.ts
  src/database/query/index.ts
  src/routes/cohorts.ts
  src/routes/index.ts
Labels: awaiting-review

#69 65 get single cohort
  src/controllers/admin/cohorts/addCohortController.ts
  src/controllers/cohorts/getSingleCohortController.ts
  src/controllers/cohorts/index.ts
  src/controllers/index.ts
  src/database/index.ts
  src/database/query/cohorts/getSingleCohortQuery.ts
  src/database/query/cohorts/index.ts
  src/database/query/index.ts
  src/routes/cohorts.ts
  src/utils/index.ts
  src/utils/types/helpers/GetSingleCohortQuery.ts
  src/utils/types/helpers/index.ts
  src/utils/types/index.ts
  src/utils/types/requests/index.ts
  src/utils/validation/cohorts/getSingleCohortSchema.ts
  src/utils/validation/cohorts/index.ts
  src/utils/validation/index.ts
Labels: awaiting-review

#71 66 edit get posts and single post route response structure
  src/controllers/posts/getCohortPostsController.ts
  src/controllers/posts/getPublicPostsController.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/posts/getCohortPostsQuery.ts
  src/database/query/posts/getCountPostsQuery.ts
  src/database/query/posts/getPostByIdQuery.ts
  src/database/query/posts/getPublicPostsQuery.ts
  src/database/query/posts/index.ts
Labels: awaiting-review, database

#74 73 refactor
  src/controllers/admin/users/addUsersController.ts
  src/database/index.ts
  src/database/query/cohorts/getCohortByIdQuery.ts
  src/database/query/cohorts/index.ts
  src/database/query/index.ts
  src/utils/index.ts
  src/utils/types/helpers/CohortIdQueryArg.ts
  src/utils/types/helpers/index.ts
  src/utils/types/index.ts
Labels: awaiting-review

#76 75 get members
  src/controllers/index.ts
  src/controllers/users/getMembersController.ts
  src/controllers/users/index.ts
  src/database/config/build.sql
  src/database/config/fakeData.sql
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/users/getCountMembersQuery.ts
  src/database/query/users/getMembersQuery.ts
  src/database/query/users/index.ts
  src/routes/index.ts
  src/routes/users.ts
Labels: awaiting-review

#79 refactor: edit addPost name in controlller folder
  src/controllers/posts/addPostController.ts
  src/controllers/posts/index.ts
Labels: awaiting-review

#80 feat: create corsOtions
  src/app.ts
Labels: awaiting-review
